name: Build

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: UEFI
  FORCE_INSTALL: 1
  HAS_OPENSSL_BUILD: 1
  HAS_OPENSSL_W32BUILD: 0
  WERROR: 1

jobs:
  build-macos:
    name: macOS XCODE5
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@v6

      - name: Install Linux Toolchain
        run: |
          brew tap FiloSottile/homebrew-musl-cross
          brew install musl-cross

      - name: Install Dependencies
        run: brew install mingw-w64

      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -LfsS https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

      - run: ./build_duet.tool
      - run: ./build_oc.tool

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: macOS XCODE5 Artifacts
          path: Binaries/*.zip

      - name: Create Release body
        run: |
          printf "**v%s**\n\n" ${GITHUB_REF/refs\/tags\//} > body.txt
          printf "* %s\n" "OcAppleSecureBootLib: Set AppleSecureBootPolicy UEFI variable only if SecureBootModel is not disabled" >> body.txt
          printf "* %s\n" "OpenLinuxBoot: add trailing space between initrd section and other Linux kernel cmdline options if there is at least one kernel option specificed with autoopts" >> body.txt
          printf "* %s\n" "Modify CrScreenshotDxe in order to be embedded in my UEFI firmware" >> body.txt
          printf "* %s\n" "Modify OpenUsbKbDxe by increasing USBKBD_REPEAT_RATE in order to match my UHCD AMI USB Driver" >> body.txt
          printf "* %s\n" "Include EnhancedFatDxe in OpenCorePkg in order to replace bugged AMI FileSystem.efi on my APTIO IV firmware" >> body.txt
          printf "* %s\n" "Modify EnhancedFatDxe by removing FAT32's FsVersion check during driver initialization" >> body.txt
          printf "* %s\n" "Include GenSec, LzmaCompress and TianoCompress BaseTools in order to help in the creation of UEFI modules" >> body.txt
          printf "* %s\n" "Add unamer and toolchain name to macOS and Windows Binaries" >> body.txt
          printf "* %s\n" "Add Windows builds to Release" >> body.txt

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: ./body.txt
          files: Binaries/*.zip

  build-linux-clangpdb:
    name: Linux CLANGPDB
    runs-on: ubuntu-24.04
    env:
      TOOLCHAINS: CLANGPDB
    steps:
      - uses: actions/checkout@v6

      - name: Apply Docker AppArmor settings
        run: |
          src=$(/usr/bin/curl -LfsS https://raw.githubusercontent.com/acidanthera/ocbuild/master/docker-apparmor.sh) && eval "$src" || exit 1

      - name: Use Docker in rootless mode.
        uses: ScribeMD/rootless-docker@0.2.2

      - name: ./build_duet.tool
        run: docker compose run build-duet

      - name: ./build_oc.tool
        run: docker compose run build-oc

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Linux CLANGPDB Artifacts
          path: Binaries/*.zip

  build-linux-gcc5:
    name: Linux GCC
    runs-on: ubuntu-24.04
    env:
      TOOLCHAINS: GCC
    steps:
      - uses: actions/checkout@v6

      - name: Apply Docker AppArmor settings
        run: |
          src=$(/usr/bin/curl -LfsS https://raw.githubusercontent.com/acidanthera/ocbuild/master/docker-apparmor.sh) && eval "$src" || exit 1

      - name: Use Docker in rootless mode.
        uses: ScribeMD/rootless-docker@0.2.2

      - name: ./build_duet.tool
        run: docker compose run build-duet

      - name: ./build_oc.tool
        run: docker compose run build-oc

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Linux GCC Artifacts
          path: Binaries/*.zip

  build-linux-clangdwarf:
    name: Linux CLANGDWARF
    runs-on: ubuntu-24.04
    env:
      TOOLCHAINS: CLANGDWARF
    steps:
      - uses: actions/checkout@v6

      - name: Apply Docker AppArmor settings
        run: |
          src=$(/usr/bin/curl -LfsS https://raw.githubusercontent.com/acidanthera/ocbuild/master/docker-apparmor.sh) && eval "$src" || exit 1

      - name: Use Docker in rootless mode.
        uses: ScribeMD/rootless-docker@0.2.2

      - name: ./build_duet.tool
        run: docker compose run build-duet

      - name: ./build_oc.tool
        run: docker compose run build-oc

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Linux CLANGDWARF Artifacts
          path: Binaries/*.zip

  build-linux-docs:
    name: Linux Docs
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Apply Docker AppArmor settings
        run: |
          src=$(/usr/bin/curl -LfsS https://raw.githubusercontent.com/acidanthera/ocbuild/master/docker-apparmor.sh) && eval "$src" || exit 1

      - name: Use Docker in rootless mode.
        uses: ScribeMD/rootless-docker@0.2.2

      - name: Docs
        run: docker compose run build-docs

  build-windows:
    name: Windows VS2022
    runs-on: windows-latest
    env:
      HAS_OPENSSL_BUILD: 0
      CC: gcc
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x86
      - name: Install Dependencies
        run: |
          choco install make nasm zip iasl --no-progress

      - name: CI Bootstrap
        run: |
          src=$(curl -LfsS https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

      - run: ./build_duet.tool
      - run: ./build_oc.tool

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Windows Artifacts
          path: Binaries/*.zip

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: Binaries/*.zip
